local rifle = {}

rifle.CONFIG = {
    debug = false,
    
    sensitivity = 0.6,      
    fov = 90, 
    dpi = 1600,      
    screenResolutionHeight = 1200,
    -- Pattern scale. Baked into the uploaded curve; reload Hammerspoon to apply.
    strength = 3,
    -- While A/D is held the helper multiplies each step by this.
    strafeMultiplier = 2.25,
    -- Standing + RMB (ADS), Ctrl not held: × this. Hip-fire / crouch = 1.0.
    standMultiplier = 1.75,
    -- Per-step magnitude jitter (±). 0.10 ≈ 90% fidelity to the base curve.
    humanJitter = 0.10,
    hidDaemonPort = 49173,
    
    basePattern = {
    {dx = 0, dy = 2, delay = 3},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 4},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 3, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 4},
    {dx = 0, dy = 2, delay = 3},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = 3, delay = 4},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 3},
    {dx = 0, dy = 1, delay = 1},
    {dx = 2, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 3},
    {dx = 0, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 4},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 37},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 2, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = -2, dy = 1, delay = 2},
    {dx = 1, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 3},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 1, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 4},
    {dx = -1, dy = 1, delay = 2},
    {dx = 0, dy = -1, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 3},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 5},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 1, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 1, dy = -1, delay = 2},
    {dx = -1, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 3},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 1, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 35},
    {dx = -2, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 3, delay = 3},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 3},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 3},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 2},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 3},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = 1, dy = 3, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 3},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 3, delay = 2},
    {dx = 0, dy = -1, delay = 2},
    {dx = 0, dy = 3, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 1, dy = -1, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = 2, delay = 3},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 4},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 2},
    {dx = 1, dy = 0, delay = 2},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 36},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -3, dy = 1, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 2},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 2},
    {dx = -1, dy = 1, delay = 3},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 1, dy = 2, delay = 3},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 3},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 2},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 3},
    {dx = -2, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 3},
    {dx = 0, dy = 3, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = 0, dy = 3, delay = 1},
    {dx = 0, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = -1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 2, delay = 37},
    {dx = 0, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 3},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 3},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 3},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 3},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 3, delay = 3},
    {dx = -1, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = -3, dy = -1, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 2, delay = 2},
    {dx = -2, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 3, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = 1, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 3, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 36},
    {dx = 0, dy = 1, delay = 1},
    {dx = 3, dy = -2, delay = 2},
    {dx = -1, dy = 1, delay = 2},
    {dx = 1, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = 0, dy = 3, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 3},
    {dx = -1, dy = -1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -3, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 3},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 3},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 3},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 35},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 1, dy = 0, delay = 2},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 3},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 3},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 2, delay = 2},
    {dx = 1, dy = 0, delay = 2},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 2},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 3},
    {dx = -2, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = -1, dy = 3, delay = 1},
    {dx = 1, dy = -1, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 3},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 3, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -1, dy = 3, delay = 1},
    {dx = 1, dy = -1, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 4},
    {dx = 1, dy = 0, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 3},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 34},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 3},
    {dx = -2, dy = 1, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 1, dy = -1, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 3, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = -1, delay = 2},
    {dx = 0, dy = 3, delay = 1},
    {dx = -2, dy = 0, delay = 3},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 3},
    {dx = -2, dy = 1, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 3, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -2, dy = 2, delay = 2},
    {dx = 1, dy = -1, delay = 1},
    {dx = -1, dy = 3, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 3},
    {dx = -2, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 3},
    {dx = -2, dy = 2, delay = 3},
    {dx = -1, dy = 3, delay = 3},
    {dx = 0, dy = 1, delay = 4},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = -2, dy = 2, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 35},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 2, delay = 2},
    {dx = -2, dy = 1, delay = 4},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = -1, delay = 2},
    {dx = 0, dy = 3, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 2},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 2, delay = 1},
    {dx = 1, dy = 0, delay = 2},
    {dx = -3, dy = 1, delay = 1},
    {dx = 0, dy = 3, delay = 3},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -2, dy = -1, delay = 1},
    {dx = 1, dy = 1, delay = 2},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 1, dy = 1, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 4},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 3, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = -1, dy = 2, delay = 3},
    {dx = 1, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 36},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 3},
    {dx = 1, dy = 2, delay = 1},
    {dx = -3, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = 0, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = 1, dy = 0, delay = 2},
    {dx = -2, dy = 1, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -1, dy = 3, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = -1, delay = 1},
    {dx = 1, dy = 3, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -1, dy = 3, delay = 2},
    {dx = 0, dy = -1, delay = 2},
    {dx = -2, dy = 1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 3},
    {dx = -2, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 3},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 35},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 1, dy = -1, delay = 2},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 3},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 3},
    {dx = -2, dy = 1, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 2},
    {dx = 0, dy = -2, delay = 1},
    {dx = 0, dy = 3, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 3},
    {dx = -2, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 3},
    {dx = -2, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 3},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -3, dy = 3, delay = 3},
    {dx = 1, dy = -1, delay = 1},
    {dx = -1, dy = 3, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 36},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 2, delay = 2},
    {dx = -2, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -2, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 2},
    {dx = -2, dy = 1, delay = 2},
    {dx = 1, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 3, delay = 4},
    {dx = -2, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = -1, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 4},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -1, dy = 3, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = -3, dy = 3, delay = 2},
    {dx = -2, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 3},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = -1, delay = 2},
    {dx = 0, dy = 3, delay = 1},
    {dx = -2, dy = 3, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = 0, dy = 3, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 3},
    {dx = -1, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 35},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 3, delay = 1},
    {dx = -1, dy = -1, delay = 2},
    {dx = 0, dy = -1, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 3},
    {dx = 1, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 2},
    {dx = -2, dy = 1, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 3},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 1, dy = 0, delay = 2},
    {dx = -1, dy = 1, delay = 1},
    {dx = -2, dy = -1, delay = 1},
    {dx = 1, dy = 3, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 3},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 34},
    {dx = 0, dy = 3, delay = 1},
    {dx = -1, dy = 0, delay = 3},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 3},
    {dx = -2, dy = 2, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 2},
    {dx = -2, dy = 1, delay = 1},
    {dx = 0, dy = -1, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 0, delay = 3},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 3, delay = 3},
    {dx = -1, dy = -1, delay = 2},
    {dx = 0, dy = 3, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 3},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 3},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = -2, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 3},
    {dx = 1, dy = 0, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 34},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 3, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 3, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = -1, delay = 1},
    {dx = 0, dy = 3, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = -2, dy = -2, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -2, dy = 2, delay = 2},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 2, delay = 3},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 2, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -3, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 3, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = 0, delay = 2},
    {dx = -2, dy = 3, delay = 2},
    {dx = -1, dy = 0, delay = 2},
    {dx = -1, dy = 0, delay = 2},
    {dx = 1, dy = 2, delay = 1},
    {dx = -3, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = -1, delay = 2},
    {dx = 0, dy = 3, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 35},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 3},
    {dx = -2, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 3},
    {dx = -2, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 2},
    {dx = -1, dy = -1, delay = 1},
    {dx = -2, dy = 3, delay = 1},
    {dx = 1, dy = -1, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = -2, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 2},
    {dx = -3, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 4},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 36},
    {dx = -1, dy = 2, delay = 2},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 4},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 3},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 1, delay = 3},
    {dx = -2, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 3, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 4},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 3},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 38},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 2},
    {dx = -1, dy = 0, delay = 3},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 1, dy = 2, delay = 1},
    {dx = -3, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 2},
    {dx = -1, dy = 1, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 3, delay = 1},
    {dx = -2, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = -1, dy = 2, delay = 3},
    {dx = 1, dy = 1, delay = 1},
    {dx = -3, dy = -1, delay = 2},
    {dx = -1, dy = -1, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -3, dy = -1, delay = 1},
    {dx = 0, dy = 3, delay = 2},
    {dx = -1, dy = 0, delay = 3},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 3},
    {dx = -2, dy = 0, delay = 3},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = -2, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 2},
    {dx = -1, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 2},
    {dx = -3, dy = 0, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = 2, dy = 1, delay = 1},
    {dx = -3, dy = 2, delay = 1},
    {dx = 1, dy = -1, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = -1, delay = 1},
    {dx = 0, dy = 3, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 1, delay = 37},
    {dx = -1, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = -2, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 1, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 2},
    {dx = 2, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 3},
    {dx = -1, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 2, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 4},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 3},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 2, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -2, dy = 3, delay = 3},
    {dx = -1, dy = 2, delay = 2},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = -1, delay = 1},
    {dx = 0, dy = 3, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = 1, dy = 2, delay = 38},
    {dx = -3, dy = -1, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 2, delay = 3},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 3},
    {dx = -2, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 4},
    {dx = -1, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 3},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 3},
    {dx = -1, dy = 2, delay = 2},
    {dx = 1, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 5},
    {dx = -2, dy = 2, delay = 3},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 3, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 1, delay = 34},
    {dx = -1, dy = 2, delay = 2},
    {dx = 0, dy = -1, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -3, dy = 2, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = 2, delay = 2},
    {dx = 1, dy = -1, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 3, delay = 3},
    {dx = -2, dy = -1, delay = 2},
    {dx = 0, dy = 3, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -3, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 4},
    {dx = -1, dy = 2, delay = 2},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = -2, dy = 0, delay = 3},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 3},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 4},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 35},
    {dx = 1, dy = -1, delay = 1},
    {dx = -1, dy = 3, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 1, dy = 3, delay = 1},
    {dx = -3, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 2},
    {dx = -1, dy = 2, delay = 1},
    {dx = -2, dy = 2, delay = 3},
    {dx = 0, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = -2, dy = 2, delay = 3},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 1, dy = 0, delay = 2},
    {dx = -3, dy = 0, delay = 1},
    {dx = 1, dy = 3, delay = 2},
    {dx = -1, dy = -1, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = -2, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 1, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 3},
    {dx = 0, dy = 3, delay = 1},
    {dx = -2, dy = -1, delay = 1},
    {dx = -1, dy = 3, delay = 1},
    {dx = 1, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = 2, delay = 2},
    {dx = -1, dy = 1, delay = 3},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 33},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 3, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 3, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 4},
    {dx = -1, dy = 1, delay = 1},
    {dx = -2, dy = 3, delay = 1},
    {dx = 1, dy = -1, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 3},
    {dx = -1, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -2, dy = 2, delay = 2},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 2},
    {dx = -2, dy = 0, delay = 2},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 2},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 36},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = 2, delay = 2},
    {dx = -1, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = 1, dy = -1, delay = 1},
    {dx = -1, dy = 3, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 3},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = 1, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 1},
    {dx = -1, dy = 3, delay = 3},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -2, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 2},
    {dx = 1, dy = -1, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = 2, delay = 3},
    {dx = 0, dy = 1, delay = 3},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 3},
    {dx = -2, dy = 2, delay = 3},
    {dx = -1, dy = 0, delay = 2},
    {dx = 1, dy = 3, delay = 1},
    {dx = -3, dy = -1, delay = 2},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 2, delay = 3},
    {dx = -2, dy = 1, delay = 36},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 3},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 3},
    {dx = -2, dy = 0, delay = 2},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 2, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -3, dy = 0, delay = 1},
    {dx = 1, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -1, dy = 1, delay = 4},
    {dx = -2, dy = 2, delay = 2},
    {dx = 0, dy = -1, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = -3, dy = 2, delay = 1},
    {dx = 1, dy = -1, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 3},
    {dx = 0, dy = 3, delay = 1},
    {dx = 0, dy = -1, delay = 2},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = -1, delay = 1},
    {dx = -2, dy = 3, delay = 1},
    {dx = 1, dy = -1, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = -2, dy = 1, delay = 4},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 2},
    {dx = 0, dy = 1, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 1, delay = 3},
    {dx = -1, dy = 2, delay = 2},
    {dx = -1, dy = 1, delay = 2},
    {dx = -2, dy = 0, delay = 3},
    {dx = 0, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = -1, delay = 1},
    {dx = -2, dy = 3, delay = 1},
    {dx = 1, dy = 0, delay = 2},
    {dx = -1, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 35},
    {dx = 1, dy = 0, delay = 1},
    {dx = -3, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 2, delay = 1},
    {dx = -1, dy = 0, delay = 2},
    {dx = 0, dy = 3, delay = 1},
    {dx = -2, dy = 1, delay = 4},
    {dx = -1, dy = 3, delay = 3},
    {dx = 0, dy = -1, delay = 1},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 3},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 3},
    {dx = -2, dy = 1, delay = 1},
    {dx = 1, dy = 0, delay = 2},
    {dx = -2, dy = 2, delay = 1},
    {dx = 0, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 2},
    {dx = -2, dy = 0, delay = 1},
    {dx = 1, dy = 0, delay = 1},
    {dx = -1, dy = 3, delay = 1},
    {dx = 1, dy = -1, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -2, dy = 1, delay = 2},
    {dx = 0, dy = 2, delay = 3},
    {dx = -1, dy = 1, delay = 3},
    {dx = -2, dy = 2, delay = 3},
    {dx = 0, dy = 1, delay = 1},
    {dx = -1, dy = 2, delay = 3},
    {dx = -2, dy = 1, delay = 2},
    {dx = 1, dy = 2, delay = 2},
    {dx = 2, dy = 0, delay = 1},
    {dx = -1, dy = 1, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 1, delay = 1},
    {dx = -2, dy = 0, delay = 2},
    {dx = -2, dy = 0, delay = 1},
    {dx = 0, dy = 2, delay = 2},
    {dx = -1, dy = 1, delay = 1},
    {dx = -2, dy = 2, delay = 3},
    {dx = -1, dy = 1, delay = 2}
    },
    
    activationSequence = {
        --[[ {dx = 1,  dy = 0}, 
        {dx = 0,  dy = 1}, 
        {dx = -1, dy = 0}, 
        {dx = 0,  dy = -1} ]]
    },
    
    calibrationSequence = {
        --[[ {dx = 0,  dy = 0,  delay = 20},   
        {dx = 1,  dy = 0,  delay = 20},   
        {dx = -1, dy = 0,  delay = 20},   
        {dx = 0,  dy = 1,  delay = 20},   
        {dx = 0,  dy = -1, delay = 20},   
        {dx = 0,  dy = 0,  delay = 20}  ]]
    }
}

rifle.STATE = {
    enabled = false,   
    shooting = false,    
    stepIndex = 1,      
    patternLength = 30,  
    currentPattern = {},  
    originalMousePosition = nil,
    compensationTimer = nil,
    isInGameMode = false,
    rawInputActivated = false,
    activationTimer = nil,
    activationCounter = 0,
    currentMethod = 1,
    calibrationStep = 1,
    patternTimeMs = 0,
    compStartedAt = 0,
    accumDx = 0,
    accumDy = 0,
    owedDx = 0,
    owedDy = 0,
    lastRealMouseAt = 0,
    deepTap = nil,
    hidSock = nil,
    hidAvailable = false,
    injecting = false,
    strafeA = false,
    strafeD = false,
    strafeTap = nil,
    patternSent = false
}

local function isRustActive()
    local app = hs.application.frontmostApplication()
    return app and (app:name() == "Rust" or string.find(app:name() or "", "RustClient"))
end

function rifle:log(msg)
    if self.CONFIG.debug and isRustActive() then
        print("[IA] " .. msg)
    end
end

--------------------------------------------------------------------
-- Input helper
--
-- A root LaunchDaemon posts pointing reports through the system
-- VirtualHID service. The curve runs inside that process; this Lua
-- module only uploads the curve and toggles start/stop on LMB.
--------------------------------------------------------------------

function rifle:hidConnected()
    local sock = self.STATE.hidSock
    if not sock then return false end
    local ok, connected = pcall(function() return sock:connected() end)
    return ok and connected
end

function rifle:hidConnect()
    -- Reuse warm connection — never block the LMB-down path with usleep/reconnect.
    if self:hidConnected() then
        self.STATE.hidAvailable = true
        return true
    end

    local port = self.CONFIG.hidDaemonPort or 49173
    if self.STATE.hidSock then
        pcall(function() self.STATE.hidSock:disconnect() end)
        self.STATE.hidSock = nil
    end

    -- A read callback must stay armed, otherwise a daemon restart goes unnoticed
    -- and `connected()` keeps reporting true while start/stop vanish.
    local sock
    sock = hs.socket.new(function(data)
        if data and (data:find("n=0", 1, true) or data:find("steps=0", 1, true)) then
            self.STATE.patternSent = false
        end
        pcall(function() sock:read("\n") end)
    end)
    sock:connect("127.0.0.1", port)
    -- Brief poll only (was 120ms sleep on every spray — felt like start delay)
    for _ = 1, 10 do
        hs.timer.usleep(5000)
        local ok, connected = pcall(function() return sock:connected() end)
        if ok and connected then
            self.STATE.hidSock = sock
            self.STATE.hidAvailable = true
            self.STATE.patternSent = false
            pcall(function() sock:read("\n") end)
            self:hidCmd(string.format("mul %.4f\n", tonumber(self.CONFIG.strafeMultiplier) or 1.25))
            self:hidCmd(string.format("stand %.4f\n", tonumber(self.CONFIG.standMultiplier) or 2.0))
            self:hidCmd(string.format("jit %.4f\n", tonumber(self.CONFIG.humanJitter) or 0.10))
            self:hidUploadPattern()
            return true
        end
    end
    self.STATE.hidAvailable = false
    return false
end

function rifle:hidCmd(line)
    if not self:hidConnected() then
        return false
    end
    local ok = pcall(function()
        self.STATE.hidSock:write(line)
    end)
    if not ok then
        self.STATE.hidAvailable = false
        self.STATE.patternSent = false
        pcall(function() self.STATE.hidSock:disconnect() end)
        self.STATE.hidSock = nil
        return false
    end
    return true
end

-- Curve file is small text deltas; name is intentionally generic.
function rifle:hidUploadPattern()
    local path = os.getenv("HOME") .. "/.hammerspoon/hidmouse/curve.dat"
    local f = io.open(path, "w")
    if not f then
        print("[IA] cannot write curve: " .. path)
        return false
    end

    local pattern = self.STATE.currentPattern or {}
    local out = {}
    for _, step in ipairs(pattern) do
        out[#out + 1] = string.format("%.4f %.4f %d", step.dx, step.dy, math.max(tonumber(step.delay) or 1, 1))
    end
    f:write(table.concat(out, "\n"))
    f:write("\n")
    f:close()

    if self:hidCmd("pat " .. path .. "\n") then
        self.STATE.patternSent = true
        if self.CONFIG.debug then
            print(string.format("[IA] curve uploaded: %d steps", #pattern))
        end
        return true
    end
    return false
end

function rifle:hidStatus()
    local port = self.CONFIG.hidDaemonPort or 49173
    local out = hs.execute(string.format("echo ping | nc -w 1 127.0.0.1 %d", port)) or ""
    return out
end

function rifle:ensureHidDaemon()
    self.STATE.hidAvailable = false

    local status = self:hidStatus()
    if not status:find("pong", 1, true) then
        print("[IA] helper not running — run hidmouse/install_daemons.sh (admin)")
        return false
    end

    if not self:hidConnect() then
        print("[IA] helper up but control socket refused")
        return false
    end

    if status:find("ready=1", 1, true) then
        if self.CONFIG.debug then
            print("[IA] pointing device ready")
        end
    else
        print("[IA] pointing not ready (" .. status:gsub("%s+$", "") .. ")")
    end
    return true
end

function rifle:stopDeepTap()
    if self.STATE.deepTap then
        self.STATE.deepTap:stop()
        self.STATE.deepTap = nil
    end
end

function rifle:stopActivationTimer()
    if self.STATE.activationTimer then
        self.STATE.activationTimer:stop()
        self.STATE.activationTimer = nil
    end
    self.STATE.rawInputActivated = false
    self.STATE.activationCounter = 0
end

function rifle:calculatePattern()
    -- basePattern = raw mouse_log deltas. Only CONFIG.strength scales them.
    local multiplier = tonumber(self.CONFIG.strength) or 1.0

    self:log(string.format("[CALC] strength=%.3f", multiplier))

    local scaledPattern = {}

    for i, step in ipairs(self.CONFIG.basePattern) do
        local scaledStep = {
            dx = step.dx * multiplier,
            dy = step.dy * multiplier,
            delay = step.delay
        }
        table.insert(scaledPattern, scaledStep)

        if self.CONFIG.debug and i <= 5 then
            self:log(string.format("[PATTERN] Step %d: dx=%.3f->%.3f, dy=%.3f->%.3f",
                i, step.dx, scaledStep.dx, step.dy, scaledStep.dy))
        end
    end

    return scaledPattern
end

function rifle:init()
    print("[IA] starting…")

    self.STATE.currentPattern = self:calculatePattern()
    self.STATE.patternLength = #self.STATE.currentPattern

    self:ensureHidDaemon()
    self:setupHotkeys()
    self:setupMouseDetection()

    -- Keep control socket warm so the first LMB has zero connect latency
    if self.STATE.hidKeepalive then
        self.STATE.hidKeepalive:stop()
    end
    self.STATE.hidKeepalive = hs.timer.new(5, function()
        if not self:hidConnected() then
            self:hidConnect()
        end
    end)
    self.STATE.hidKeepalive:start()

    print(string.format("[IA] ready | strength=%.2f | jitter=%.2f | hid=%s",
        tonumber(self.CONFIG.strength) or 1,
        tonumber(self.CONFIG.humanJitter) or 0.10,
        tostring(self.STATE.hidAvailable)))
end

function rifle:setupHotkeys()

    self.mouseTap = hs.eventtap.new({hs.eventtap.event.types.otherMouseDown}, function(event)
        if event:getProperty(hs.eventtap.event.properties.mouseEventButtonNumber) == 3 then
            self:toggleSystem()
            return true
        end
        return false
    end)

    self.mouseTap:start()

end

function rifle:detectGameMode()
    local rustApp = hs.application.get("Rust") or hs.application.get("RustClient")
    if rustApp then
        local mainWindow = rustApp:mainWindow()
        if mainWindow then
            self.STATE.isInGameMode = mainWindow:isFullScreen()
            if self.CONFIG.debug then
                self:log(string.format("[MODE] Fullscreen mode: %s", 
                    tostring(self.STATE.isInGameMode)))
            end
        end
    else
        self.STATE.isInGameMode = false
    end
end

function rifle:resetState()
    self.STATE.stepIndex = 1
    self.STATE.currentMethod = 1
    self.STATE.calibrationStep = 1
    self:stopActivationTimer()
end

function rifle:toggleSystem()
    self.STATE.enabled = not self.STATE.enabled
    local status = self.STATE.enabled and "ON" or "OFF"
    print("[IA] " .. status)
    hs.alert.show("Assist: " .. status, 1)

    -- sync to menu window
    local stateFile = os.getenv("HOME") .. "/.hammerspoon/macro_state.json"
    local f = io.open(stateFile, "w")
    if f then
        f:write('{"enabled":' .. tostring(self.STATE.enabled) .. '}')
        f:close()
    end

    if not self.STATE.enabled then
        self:stopShooting()
        self:resetState()
    end
end

function rifle:setupMouseDetection()
    if self.mouseEventWatcher then
        self.mouseEventWatcher:stop()
    end
    
    self.mouseEventWatcher = hs.eventtap.new(
        { hs.eventtap.event.types.leftMouseDown, 
          hs.eventtap.event.types.leftMouseUp },
        function(event)
            if not self.STATE.enabled then return false end
            if not isRustActive() then return false end
            
            local eventType = event:getType()
            
            if eventType == hs.eventtap.event.types.leftMouseDown then
                if not self.STATE.shooting then
                    self.STATE.originalMousePosition = hs.mouse.absolutePosition()
                    self:resetState()
                    -- Compensation first — detectGameMode/logging must not delay the spray.
                    self:startShooting()
                    hs.timer.doAfter(0, function()
                        self:detectGameMode()
                        self:log(string.format("[START] Pos: %.0f,%.0f | Mode: %s | hid=%s",
                            self.STATE.originalMousePosition.x, self.STATE.originalMousePosition.y,
                            self.STATE.isInGameMode and "Game" or "Menu",
                            tostring(self:hidConnected())))
                    end)
                end
                
            elseif eventType == hs.eventtap.event.types.leftMouseUp then
                if self.STATE.shooting then
                    self:log("Left mouse button released - stop")
                    self:stopShooting()
                end
            end
            
            return false
        end
    )
    
    self.mouseEventWatcher:start()
    self:log("Mouse detection enabled")
end

function rifle:startShooting()
    if not self.STATE.enabled or self.STATE.shooting or not isRustActive() then
        return
    end

    self.STATE.shooting = true
    self.STATE.stepIndex = 1
    self.STATE.currentMethod = 1
    self.STATE.patternTimeMs = 0
    self.STATE.owedDx = 0
    self.STATE.owedDy = 0
    self.STATE.lastRealMouseAt = 0
    -- Start the clock / first steps immediately — no HID reconnect before spray.
    self.STATE.compStartedAt = hs.timer.secondsSinceEpoch()

    self:log(string.format("run start | n=%d | hid=%s | strength=%.2f",
        self.STATE.patternLength, tostring(self:hidConnected()), tonumber(self.CONFIG.strength) or 1))

    if not self.STATE.patternSent then
        self:hidUploadPattern()
    end
    self:hidCmd("start\n")
    self:startFocusWatchdog()

    -- Reconnect in background only if the warm socket died (must not delay first bullets)
    if not self:hidConnected() then
        hs.timer.doAfter(0, function()
            if not self.STATE.shooting then return end
            if not self.STATE.hidAvailable then
                self:ensureHidDaemon()
            else
                self:hidConnect()
            end
            if self.STATE.shooting then
                self:hidCmd("start\n")
            end
        end)
    end
end

-- The daemon drives the pattern; Lua only has to notice that Rust lost focus.
function rifle:startFocusWatchdog()
    if self.compensationTimer then
        self.compensationTimer:stop()
    end
    self.compensationTimer = hs.timer.new(0.1, function()
        if self.STATE.shooting and not isRustActive() then
            self:stopShooting()
        end
    end)
    self.compensationTimer:start()
end

function rifle:stopShooting()
    if not self.STATE.shooting then
        return
    end

    self.STATE.shooting = false
    self.STATE.patternTimeMs = 0
    self.STATE.owedDx = 0
    self.STATE.owedDy = 0

    self:hidCmd("stop\n")

    if self.compensationTimer then
        self.compensationTimer:stop()
        self.compensationTimer = nil
    end

    self:stopDeepTap()
    self:stopActivationTimer()

    self:log("run stop")

    self:resetState()
end

return rifle